version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - unused
    
nolint:
  enable: true
  require-explanation: true

run:
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*_gen.go"

issues:
  exclude-rules:
    - linters:
        - errcheck
      path: pkg/server/router.go
      text: "Error return value of `w.Write` is not checked"
    - linters:
        - govet
      path: pkg/server/server.go
      text: "the cancel function returned by context.WithTimeout should be called"
