version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - unused

run:
  tests: true

skip-dirs:
  - vendor

skip-files:
  - ".*_gen.go"

issues:
  exclude:
    - path: pkg/server/router.go
      text: "Error return value of `w.Write` is not checked"
    - path: pkg/server/server.go
      text: "the cancel function returned by context.WithTimeout should be called"
