services:
  mcptls:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    environment:
      MCPTLS_ENABLED: "false"
      MCPTLS_SERVER_PORT: "8080"
      MCPTLS_SERVER_ADDR: "0.0.0.0:8080"
    volumes:
      - ./certs:/root/certs:ro
    restart: unless-stopped
