services:
  mcptls:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "9090:9090"
    environment:
      MCPTLS_ENABLED: "false"
      MCPTLS_SERVER_PORT: "9090"
      MCPTLS_SERVER_ADDR: "0.0.0.0:9090"
    restart: unless-stopped
