version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-tls-server
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=mcp_tls_schema
      - MONGO_COLLECTION=messages
    ports:
      - "8080:8080"
    networks:
      - appnet

  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet

volumes:
  mongo_data:

networks:
  appnet:
    driver: bridge
